services:
  postgres:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=stratospheric
      - POSTGRES_PASSWORD=stratospheric
      - POSTGRES_DB=stratospheric
  localstack:
    image: localstack/localstack:3.2.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,dynamodb
    volumes:
      - ./src/test/resources/localstack/local-aws-infrastructure.sh:/etc/localstack/init/ready.d/init.sh
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    ports:
      - "8888:8080"
    environment:
      - KEYCLOAK_ADMIN=keycloak
      - KEYCLOAK_ADMIN_PASSWORD=keycloak
      - DB_VENDOR=h2
    command: start-dev --import-realm
    volumes:
      - ./src/test/resources/keycloak/stratospheric-realm.json:/opt/keycloak/data/import/stratospheric-realm.json