spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: validate
    open-in-view: false
cloud:
  aws:
    stack:
      auto: false
    region:
      static: eu-west-2
      auto: false
    instance:
      data:
        enabled: false
    sns:
      enabled: false

error:
  handling:
    exception-logging: WITH_STACKTRACE

server:
  forward-headers-strategy: framework

