spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: validate
    open-in-view: false
  application:
    name: stratospheric-app

logging:
  level:
    org.springframework.web.socker.server: DEBUG
    org.springframework.security.messaging.web.socket: DEBUG
    org.springframework.messaging: DEBUG

cloud:
  aws:
    stack:
      auto: false
    region:
      static: eu-west-2
      auto: false
    instance:
      data:
        enabled: false
    sns:
      enabled: false

error:
  handling:
    exception-logging: WITH_STACKTRACE

server:
  forward-headers-strategy: framework

custom:
  invitation-codes: DUKE, HELLO_WORLD, STRATOSPHERIC # TODO: outsource them -> e.g. env variable or database

