name: Build image and deploy to ECR

on:
  workflow_dispatch

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'maven'
        
    - name: NPM install
      working-directory: cdk
      run: npm install
      
    - name: Deploy ECR
      working-directory: cdk
      run: npm run ecr-registry:deploy
        
    - name: Build application
      working-directory: application
      run: ./mvnw clean package
      
    - name: Create Docker image tag
      id: dockerImageTag
      run: echo "::set-output name=tag::$(date +'%Y%m%d%H%M%S')-${GITHUB_SHA}"
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: todo-app
        DOCKER_IMAGE_TAG: ${{ steps.dockerImageTag.outputs.tag }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${DOCKER_IMAGE_TAG} .
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:${DOCKER_IMAGE_TAG}
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${DOCKER_IMAGE_TAG}
        
    - name: Deploy app
      working-directory: cdk
      run: npm run app:deploy