name: Build image and deploy to ECR

on:
  workflow_dispatch

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ROLE_TO_ASSUME : ${{ secrets.AWS_ROLE_TO_ASSUME }}

permissions:
  id-token: write

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      
    - name: Destroy ECR
      working-directory: cdk
      run: npm run ecr-registry:destroy
        
    - name: Destroy app
      working-directory: cdk
      run: npm run app:destroy